# Generated by Django 5.2.8 on 2025-12-02 10:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('structure_score', models.IntegerField(default=0)),
                ('link_score', models.IntegerField(default=0)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analysis_time', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url'], name='analyzer_an_url_7cedee_idx'), models.Index(fields=['created_at'], name='analyzer_an_created_58f922_idx'), models.Index(fields=['status'], name='analyzer_an_status_df26d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_details', models.JSONField(default=dict)),
                ('content_details', models.JSONField(default=dict)),
                ('structure_details', models.JSONField(default=dict)),
                ('link_details', models.JSONField(default=dict)),
                ('ai_recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='analyzer.analysisreport')),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_time', models.FloatField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint'], name='analyzer_ap_endpoin_dac186_idx'), models.Index(fields=['created_at'], name='analyzer_ap_created_06aaa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this report', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this analysis')),
                ('session_id', models.CharField(blank=True, help_text='For tracking without login', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='analyzer.analysisreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='analyzer_sa_session_c5dd14_idx'), models.Index(fields=['created_at'], name='analyzer_sa_created_40c984_idx')],
            },
        ),
    ]
